; Raynet Installer Framework 0.3

[Paths]
LogRoot=C:\ProgramData\Raynet\Intune\Apps\Logs
DetectionRoot=HKLM:\Software\Raynet\IntuneDetection

[Logging]
Level=INFO
PackageSubdirectory=true
ComponentLogs=true

[Framework]
CreateMissingDirectories=true
